[package]
name = "specter-cli"
version = "0.1.0"
edition = "2021"
description = "CLI for the Specter protocol"

[dependencies]
specter-core = { path = "../specter-core" }
specter-primitives = { path = "../specter-primitives" }
specter-blind-sig = { path = "../specter-blind-sig" }
specter-credential = { path = "../specter-credential" }
curve25519-dalek = { workspace = true }
serde = { workspace = true }
serde_json = "1"
hex = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
chacha20poly1305 = { workspace = true }
rand_core = { workspace = true }
zeroize = { workspace = true }
subtle = { workspace = true }
