//! Token minting (issuance) via threshold blind signatures.

use curve25519_dalek::RistrettoPoint;

use specter_blind_sig::threshold::{self, SignerId, ThresholdKeyset};
use specter_credential::credential::Attributes;
use specter_credential::issuer::Issuer;
use specter_credential::presentation;
use specter_fold::accumulator::{self, TransferState};
use specter_primitives::pedersen::PedersenParams;
use specter_primitives::scalar_utils::{random_scalar, scalar_from_u64};

use curve25519_dalek::Scalar;

use crate::token::ProofCarryingToken;

/// User-generated private values for token issuance.
///
/// SECURITY: These values are generated by the USER, not the mint.
/// The mint never learns token_id, owner_secret, or value_blinding.
/// This ensures the blind signature provides real unlinkability.
pub struct UserTokenSecrets {
    pub token_id: [u8; 32],
    pub owner_secret: [u8; 32],
    pub value_blinding: Scalar,
    pub value_commitment: RistrettoPoint,
}

impl Drop for UserTokenSecrets {
    fn drop(&mut self) {
        use zeroize::Zeroize;
        self.owner_secret.zeroize();
        self.value_blinding.zeroize();
    }
}

impl UserTokenSecrets {
    /// Generate fresh private values for a new token.
    pub fn generate(value: u64, pedersen: &PedersenParams) -> Self {
        let mut token_id = [0u8; 32];
        let mut owner_secret = [0u8; 32];
        use rand::RngCore;
        rand::thread_rng().fill_bytes(&mut token_id);
        rand::thread_rng().fill_bytes(&mut owner_secret);

        let value_scalar = scalar_from_u64(value);
        let value_blinding = random_scalar();
        let value_commitment = pedersen.commit(&value_scalar, &value_blinding);

        Self {
            token_id,
            owner_secret,
            value_blinding,
            value_commitment,
        }
    }
}

/// Configuration for the mint.
pub struct MintConfig {
    pub threshold: usize,
    pub total_signers: usize,
    pub recursion_bound: u32,
}

/// The Mint: issues new Proof-Carrying Tokens.
pub struct Mint {
    pub keyset: ThresholdKeyset,
    pub pedersen: PedersenParams,
    pub credential_issuer: Issuer,
    pub recursion_bound: u32,
}

impl Mint {
    /// Set up a mint using a trusted dealer (for testing/prototyping).
    pub fn setup(config: MintConfig) -> Self {
        let keyset = threshold::dealer_keygen(config.threshold, config.total_signers);
        let pedersen = PedersenParams::new();
        let credential_issuer = Issuer::new();
        Self {
            keyset,
            pedersen,
            credential_issuer,
            recursion_bound: config.recursion_bound,
        }
    }

    /// Set up a mint using interactive DKG (no trusted dealer).
    /// No single party ever knows the full group secret key.
    pub fn setup_with_dkg(config: MintConfig) -> Self {
        let ids: Vec<u64> = (1..=config.total_signers as u64).collect();
        let keysets = specter_blind_sig::dkg::run_dkg(config.threshold, &ids)
            .expect("DKG failed");

        // Merge shares from all participants (for local simulation)
        let mut combined = keysets[&1].clone();
        for (&id, ks) in &keysets {
            if let Some(share) = ks.shares.get(&id) {
                combined.shares.insert(id, share.clone());
            }
        }

        let pedersen = PedersenParams::new();
        let credential_issuer = Issuer::new();
        Self {
            keyset: combined,
            pedersen,
            credential_issuer,
            recursion_bound: config.recursion_bound,
        }
    }

    /// Issue a new token with the given value and optional features.
    ///
    /// - `attributes`: compliance credential (KYC, sanctions, etc.)
    /// - `vdf_iterations`: if set, creates a VDF time-lock proof
    /// - `bond_owner_id`: if set, links the token to a reputation bond
    pub fn issue(
        &self,
        value: u64,
        signers: &[SignerId],
        attributes: Option<&Attributes>,
    ) -> Result<ProofCarryingToken, MintError> {
        self.issue_full(value, signers, attributes, None, None)
    }

    /// Issue with all optional features.
    ///
    /// SECURITY: The user generates token_id, owner_secret, and value_blinding
    /// BEFORE contacting the mint. The mint never learns these private values.
    /// The mint only signs the blinded commitment.
    pub fn issue_full(
        &self,
        value: u64,
        signers: &[SignerId],
        attributes: Option<&Attributes>,
        vdf_iterations: Option<u64>,
        bond_owner_id: Option<[u8; 32]>,
    ) -> Result<ProofCarryingToken, MintError> {
        if value == 0 {
            return Err(MintError::InvalidValue);
        }

        // USER generates all private values (mint never sees these)
        let user_secrets = UserTokenSecrets::generate(value, &self.pedersen);

        // Mint only sees the commitment (not the opening)
        let token_id = user_secrets.token_id;
        let owner_secret = user_secrets.owner_secret;
        let blinding = user_secrets.value_blinding;
        let value_commitment = user_secrets.value_commitment;

        // Threshold blind sign
        let signed_msg = build_signed_message(&token_id, &value_commitment);
        let signature = threshold::threshold_blind_sign(&self.keyset, signers, &signed_msg)
            .map_err(|e| MintError::SigningFailed(e.to_string()))?;

        // Create initial fold proof
        let mut owner_hash = [0u8; 32];
        owner_hash.copy_from_slice(&specter_primitives::scalar_utils::hash_to_scalar(&owner_secret).as_bytes()[..32]);
        let genesis_state = TransferState {
            token_id,
            owner_hash,
            step: 0,
        };
        let fold_proof = accumulator::create_initial_proof(&genesis_state);

        // Issue compliance credential if attributes provided
        let credential = attributes.map(|attrs| self.credential_issuer.issue(attrs));

        // Create compliance presentation if credential exists
        let pres = credential.as_ref().map(|cred| {
            presentation::create_presentation(
                cred,
                &[presentation::ATTR_KYC_PASSED, presentation::ATTR_NOT_SANCTIONED],
                &self.credential_issuer.pedersen,
            )
        });

        // Hash chain genesis
        let hash_chain_head = crate::token::advance_hash_chain(&[0u8; 32], &token_id);

        // VDF time-lock (if requested)
        let vdf_proof = vdf_iterations.map(|iters| {
            let seed = specter_offline::vdf::create_seed(&token_id, 0);
            specter_offline::vdf::evaluate(&seed, iters)
        });

        // Create ZK proof of value (proves commitment contains claimed value
        // WITHOUT revealing the blinding factor)
        let value_proof = self.pedersen.prove_value(&scalar_from_u64(value), &blinding);

        Ok(ProofCarryingToken {
            token_id,
            value,
            value_commitment,
            value_proof,
            mint_signature: signature,
            owner_secret,
            hash_chain_head,
            transfer_count: 0,
            recursion_bound: self.recursion_bound,
            fold_proof,
            genesis_owner_hash: owner_hash,
            credential,
            presentation: pres,
            vdf_proof,
            bond_owner_id,
        })
    }

    /// Get the group public key (used for verification).
    pub fn group_public_key(&self) -> RistrettoPoint {
        self.keyset.group_public
    }

    /// Split a token: burn one token, issue multiple tokens summing to same value.
    /// Used for making change (e.g., split a 1000-token into 750 + 250).
    ///
    /// SECURITY: Fully verifies the input token before trusting `old_token.value`.
    /// Without this check an attacker could tamper the plaintext `value` field on
    /// a legitimately-minted token and mint an arbitrary amount of fresh tokens
    /// (infinite-money attack: the nullifier derives from token_id+owner_secret
    /// alone, so the same nullifier burns regardless of the tampered value,
    /// while the new outputs are signed with the attacker's chosen values).
    pub fn split(
        &self,
        old_token: &crate::token::ProofCarryingToken,
        output_values: &[u64],
        signers: &[SignerId],
        nullifier_set: &mut crate::nullifier::NullifierSet,
    ) -> Result<Vec<crate::token::ProofCarryingToken>, MintError> {
        // 0. Full verification of the input token — the plaintext `value` field
        // is untrusted until the value-commitment binding is checked.
        let vr = crate::verify::verify_token(
            old_token,
            &self.keyset.group_public,
            &self.pedersen,
            &self.credential_issuer.pedersen,
            0, // skip expiry for split — wallet validates time separately
        );
        if !vr.signature_valid {
            return Err(MintError::SigningFailed(
                "input token mint signature invalid".into(),
            ));
        }
        if !vr.value_valid {
            return Err(MintError::SigningFailed(
                "input token value commitment invalid".into(),
            ));
        }
        if !vr.within_bound {
            return Err(MintError::SigningFailed(
                "input token exceeds recursion bound".into(),
            ));
        }
        if !vr.fold_valid {
            return Err(MintError::SigningFailed(
                "input token fold proof invalid".into(),
            ));
        }

        // Validate all output values BEFORE burning the nullifier
        for &v in output_values {
            if v == 0 {
                return Err(MintError::InvalidValue);
            }
        }

        // Verify value conservation using checked arithmetic to prevent overflow
        let total_out: u64 = output_values
            .iter()
            .try_fold(0u64, |acc, &v| acc.checked_add(v))
            .ok_or(MintError::ValueMismatch {
                input: old_token.value,
                output: u64::MAX,
            })?;
        if total_out != old_token.value {
            return Err(MintError::ValueMismatch {
                input: old_token.value,
                output: total_out,
            });
        }

        // Issue new tokens BEFORE burning the nullifier to ensure atomicity
        let new_tokens: Vec<crate::token::ProofCarryingToken> = output_values
            .iter()
            .map(|&v| self.issue(v, signers, None))
            .collect::<Result<Vec<_>, _>>()?;

        // Verify commitment-level conservation (defense-in-depth):
        // Sum of output value commitments should equal the input commitment
        // when using the same Pedersen parameters, because:
        //   C_in = v_in*G + r_in*H
        //   C_out_i = v_i*G + r_i*H
        //   sum(C_out_i) = sum(v_i)*G + sum(r_i)*H
        // Since sum(v_i) == v_in (checked above), the difference
        // sum(C_out) - C_in = (sum(r_i) - r_in)*H, which is non-zero
        // due to different random blinding factors. So we verify each
        // output's value proof individually instead.
        for new_token in &new_tokens {
            let value_scalar = scalar_from_u64(new_token.value);
            if !self.pedersen.verify_value_proof(
                &new_token.value_commitment,
                &value_scalar,
                &new_token.value_proof,
            ) {
                return Err(MintError::SigningFailed("output value proof invalid".into()));
            }
        }

        // Burn old token (publish nullifier) only after successful issuance
        let nullifier = old_token.compute_nullifier();
        if !nullifier_set.insert(nullifier) {
            return Err(MintError::SigningFailed("token already spent".into()));
        }

        Ok(new_tokens)
    }
}

/// Build the message that gets threshold-blind-signed.
pub fn build_signed_message(token_id: &[u8; 32], value_commitment: &RistrettoPoint) -> Vec<u8> {
    let mut msg = Vec::new();
    msg.extend_from_slice(token_id);
    msg.extend_from_slice(value_commitment.compress().as_bytes());
    msg
}

/// Errors during minting.
#[derive(Debug, thiserror::Error)]
pub enum MintError {
    #[error("signing failed: {0}")]
    SigningFailed(String),

    #[error("invalid value: token value must be > 0")]
    InvalidValue,

    #[error("value mismatch: input {input} != output {output}")]
    ValueMismatch { input: u64, output: u64 },
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_mint() -> Mint {
        Mint::setup(MintConfig {
            threshold: 2,
            total_signers: 3,
            recursion_bound: 20,
        })
    }

    fn test_attrs() -> Attributes {
        Attributes {
            kyc_passed: true,
            not_sanctioned: true,
            jurisdiction: "EU".to_string(),
            age_over_18: true,
            expires_at: 0,
        }
    }

    #[test]
    fn test_mint_without_credential() {
        let mint = test_mint();
        let token = mint.issue(1000, &[1, 2], None).unwrap();
        assert_eq!(token.value, 1000);
        assert!(token.credential.is_none());
        assert!(token.presentation.is_none());
        assert_eq!(token.fold_proof.steps, 0);
    }

    #[test]
    fn test_mint_with_credential() {
        let mint = test_mint();
        let attrs = test_attrs();
        let token = mint.issue(1000, &[1, 2], Some(&attrs)).unwrap();
        assert!(token.credential.is_some());
        assert!(token.presentation.is_some());
    }

    #[test]
    fn test_mint_verify_roundtrip() {
        let mint = test_mint();
        let token = mint.issue(500, &[1, 3], Some(&test_attrs())).unwrap();

        let result = crate::verify::verify_token(
            &token,
            &mint.group_public_key(),
            &mint.pedersen,
            &mint.credential_issuer.pedersen,
            0,
        );
        assert!(result.all_valid());
    }
}
