//! Threshold Blind Schnorr Signatures.
//!
//! Combines Shamir secret sharing with the Schnorr blind signature protocol
//! to create t-of-n threshold blind signatures. A subset of t signers can
//! jointly produce a blind signature without any single signer knowing the
//! message or the final signature.
//!
//! Protocol:
//! 1. **Setup (dealer mode)**: A trusted dealer generates the group keypair
//!    and distributes key shares via Shamir secret sharing.
//! 2. **Signing**: Each participating signer generates a nonce share, commits,
//!    and produces a partial response. The requester blinds the challenge,
//!    collects partial responses, combines them, and unblinds.
//!
//! Note: This uses a simplified dealer-based DKG. A real deployment would
//! use an interactive DKG protocol (e.g., Pedersen DKG or FROST DKG).

use curve25519_dalek::constants::RISTRETTO_BASEPOINT_POINT as G;
use curve25519_dalek::{RistrettoPoint, Scalar};
use std::collections::HashMap;

use specter_primitives::scalar_utils::random_scalar;
use specter_primitives::shamir::{self, Share};

use crate::schnorr_blind;
use crate::types::BlindSignature;

/// Identifier for a signer in the threshold scheme.
pub type SignerId = u64;

/// A threshold keyset generated by a trusted dealer.
pub struct ThresholdKeyset {
    /// The group public key (used for verification).
    pub group_public: RistrettoPoint,
    /// Threshold: minimum number of signers required.
    pub threshold: usize,
    /// Total number of signers.
    pub total: usize,
    /// Key shares for each signer (signer_id -> secret share).
    pub shares: HashMap<SignerId, Share>,
    /// Public key shares for each signer (signer_id -> pk_i = share_i * G).
    pub public_shares: HashMap<SignerId, RistrettoPoint>,
}

/// Session state for one signer during threshold blind signing.
pub struct SignerSessionState {
    /// The signer's nonce for this session.
    pub nonce: Scalar,
    /// The signer's nonce commitment R_i = nonce * G.
    pub nonce_commitment: RistrettoPoint,
}

/// Generate a threshold keyset using a trusted dealer.
///
/// The dealer generates a random group secret key, splits it via Shamir,
/// and distributes shares. In production, this would be replaced by
/// an interactive DKG protocol.
pub fn dealer_keygen(threshold: usize, total: usize) -> ThresholdKeyset {
    let group_secret = random_scalar();
    let group_public = group_secret * G;

    let shamir_shares = shamir::split_secret(&group_secret, threshold, total)
        .expect("invalid threshold/total parameters");

    let mut shares = HashMap::new();
    let mut public_shares = HashMap::new();

    for (i, share) in shamir_shares.into_iter().enumerate() {
        let signer_id = (i + 1) as SignerId;
        public_shares.insert(signer_id, share.y * G);
        shares.insert(signer_id, share);
    }

    ThresholdKeyset {
        group_public,
        threshold,
        total,
        shares,
        public_shares,
    }
}

/// Start a signing session for one signer.
///
/// Returns the session state (kept private) and the nonce commitment
/// R_i = k_i * G (shared with other signers and the requester).
pub fn signer_start_session() -> SignerSessionState {
    let nonce = random_scalar();
    let nonce_commitment = nonce * G;
    SignerSessionState {
        nonce,
        nonce_commitment,
    }
}

/// A signer produces their partial response to a blinded challenge.
///
/// s_i = k_i + challenge * share_i
pub fn signer_partial_response(
    session: &SignerSessionState,
    blinded_challenge: &Scalar,
    key_share: &Share,
) -> Scalar {
    session.nonce + blinded_challenge * key_share.y
}

/// Perform threshold blind signing.
///
/// This orchestrates the full protocol:
/// 1. Selected signers generate nonce shares.
/// 2. Nonce commitments are combined: R = sum(R_i).
/// 3. The requester blinds the challenge using the combined R.
/// 4. Each signer produces a partial response.
/// 5. Partial responses are combined via Lagrange interpolation.
/// 6. The requester unblinds to get the final signature.
///
/// Returns the blind signature verifiable against the group public key.
pub fn threshold_blind_sign(
    keyset: &ThresholdKeyset,
    signer_ids: &[SignerId],
    message: &[u8],
) -> Result<BlindSignature, ThresholdError> {
    if signer_ids.len() < keyset.threshold {
        return Err(ThresholdError::InsufficientSigners {
            needed: keyset.threshold,
            got: signer_ids.len(),
        });
    }

    // Verify all signer IDs are valid and unique
    let mut seen = std::collections::HashSet::new();
    for &id in signer_ids {
        if !keyset.shares.contains_key(&id) {
            return Err(ThresholdError::UnknownSigner(id));
        }
        if !seen.insert(id) {
            return Err(ThresholdError::DuplicateSigner(id));
        }
    }

    // Step 1: Each signer generates a nonce session
    let sessions: Vec<SignerSessionState> = signer_ids
        .iter()
        .map(|_| signer_start_session())
        .collect();

    // Step 2: Combine nonce commitments: R = sum(R_i)
    let combined_r: RistrettoPoint = sessions
        .iter()
        .map(|s| s.nonce_commitment)
        .fold(RistrettoPoint::default(), |acc, r| acc + r);

    // Step 3: Requester blinds the challenge (first pass, will be recomputed)
    let (_blinding_factors, _blinded_challenge) =
        schnorr_blind::blind_challenge(&combined_r, &keyset.group_public, message);

    // Step 5: Combine partial responses using Lagrange coefficients
    // s' = sum(lambda_i * s_i) where lambda_i is the Lagrange coefficient
    // But for the nonce part, we just sum: sum(k_i)
    // For the secret part: sum(lambda_i * share_i * challenge) = challenge * secret
    // So: s' = sum(k_i) + challenge * sum(lambda_i * share_i)
    //        = sum(k_i) + challenge * group_secret

    // Actually, we need to weight the partial responses by Lagrange coefficients:
    // s_i = k_i + challenge * y_i
    // We want: s' = sum(k_i) + challenge * sum(lambda_i * y_i)
    //            = sum(k_i) + challenge * secret  (by Lagrange reconstruction)
    //
    // But s_i already has the y_i term without lambda_i weighting.
    // So: s' = sum(lambda_i * s_i)
    //        = sum(lambda_i * k_i) + challenge * sum(lambda_i * y_i)
    //        = sum(lambda_i * k_i) + challenge * secret
    //
    // The nonce part sum(lambda_i * k_i) is NOT the same as sum(k_i).
    // This means the combined R must also use Lagrange coefficients.
    //
    // Alternative approach (simpler): weight the nonce commitments too.
    // R = sum(lambda_i * R_i), then s' = sum(lambda_i * s_i)
    // This ensures s'*G = R + challenge * PK.

    let lagrange_coeffs = compute_lagrange_coefficients(signer_ids, &keyset.shares);

    // Recompute R with Lagrange weighting
    let weighted_r: RistrettoPoint = sessions
        .iter()
        .zip(signer_ids.iter())
        .map(|(s, &id)| lagrange_coeffs[&id] * s.nonce_commitment)
        .fold(RistrettoPoint::default(), |acc, r| acc + r);

    // Re-blind with the weighted R
    let (blinding_factors, blinded_challenge) =
        schnorr_blind::blind_challenge(&weighted_r, &keyset.group_public, message);

    // Re-compute partial responses with the new challenge
    let s_prime: Scalar = signer_ids
        .iter()
        .zip(sessions.iter())
        .map(|(&id, session)| {
            let share = &keyset.shares[&id];
            let partial = session.nonce + blinded_challenge * share.y;
            lagrange_coeffs[&id] * partial
        })
        .fold(Scalar::ZERO, |acc, s| acc + s);

    // Step 6: Unblind
    let sig = schnorr_blind::unblind_signature(
        &s_prime,
        &blinding_factors,
        &weighted_r,
        &keyset.group_public,
        message,
    );

    Ok(sig)
}

/// Compute Lagrange coefficients for the given signer IDs.
///
/// lambda_i = product_{j != i} (0 - x_j) / (x_i - x_j)
fn compute_lagrange_coefficients(
    signer_ids: &[SignerId],
    shares: &HashMap<SignerId, Share>,
) -> HashMap<SignerId, Scalar> {
    let mut coeffs = HashMap::new();

    for &i in signer_ids {
        let xi = shares[&i].x;
        let mut lambda = Scalar::ONE;

        for &j in signer_ids {
            if i == j {
                continue;
            }
            let xj = shares[&j].x;
            // lambda_i *= (0 - x_j) / (x_i - x_j) = -x_j / (x_i - x_j)
            lambda *= (-xj) * (xi - xj).invert();
        }

        coeffs.insert(i, lambda);
    }

    coeffs
}

/// Errors for the threshold blind signature scheme.
#[derive(Debug, thiserror::Error)]
pub enum ThresholdError {
    #[error("insufficient signers: need {needed}, got {got}")]
    InsufficientSigners { needed: usize, got: usize },

    #[error("unknown signer ID: {0}")]
    UnknownSigner(SignerId),

    #[error("duplicate signer ID: {0}")]
    DuplicateSigner(SignerId),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schnorr_blind;

    #[test]
    fn test_threshold_2_of_3_sign_and_verify() {
        let keyset = dealer_keygen(2, 3);
        let message = b"threshold blind signed token";

        let sig = threshold_blind_sign(&keyset, &[1, 2], message).unwrap();
        assert!(schnorr_blind::verify(&keyset.group_public, message, &sig));
    }

    #[test]
    fn test_threshold_3_of_5_sign_and_verify() {
        let keyset = dealer_keygen(3, 5);
        let message = b"3-of-5 threshold token";

        let sig = threshold_blind_sign(&keyset, &[1, 3, 5], message).unwrap();
        assert!(schnorr_blind::verify(&keyset.group_public, message, &sig));
    }

    #[test]
    fn test_different_signer_subsets_produce_valid_sigs() {
        let keyset = dealer_keygen(2, 4);
        let message = b"subset test";

        let sig1 = threshold_blind_sign(&keyset, &[1, 2], message).unwrap();
        let sig2 = threshold_blind_sign(&keyset, &[3, 4], message).unwrap();
        let sig3 = threshold_blind_sign(&keyset, &[1, 4], message).unwrap();

        assert!(schnorr_blind::verify(&keyset.group_public, message, &sig1));
        assert!(schnorr_blind::verify(&keyset.group_public, message, &sig2));
        assert!(schnorr_blind::verify(&keyset.group_public, message, &sig3));
    }

    #[test]
    fn test_insufficient_signers_fails() {
        let keyset = dealer_keygen(3, 5);
        let message = b"should fail";

        let result = threshold_blind_sign(&keyset, &[1, 2], message);
        assert!(result.is_err());
    }

    #[test]
    fn test_wrong_message_verification_fails() {
        let keyset = dealer_keygen(2, 3);
        let message = b"correct message";

        let sig = threshold_blind_sign(&keyset, &[1, 2], message).unwrap();
        assert!(!schnorr_blind::verify(
            &keyset.group_public,
            b"wrong message",
            &sig
        ));
    }

    #[test]
    fn test_wrong_pubkey_verification_fails() {
        let keyset1 = dealer_keygen(2, 3);
        let keyset2 = dealer_keygen(2, 3);
        let message = b"test";

        let sig = threshold_blind_sign(&keyset1, &[1, 2], message).unwrap();
        assert!(!schnorr_blind::verify(&keyset2.group_public, message, &sig));
    }

    #[test]
    fn test_unknown_signer_rejected() {
        let keyset = dealer_keygen(2, 3);
        let result = threshold_blind_sign(&keyset, &[1, 99], b"test");
        assert!(result.is_err());
    }

    #[test]
    fn test_unlinkability() {
        let keyset = dealer_keygen(2, 3);
        let message = b"same message";

        let sig1 = threshold_blind_sign(&keyset, &[1, 2], message).unwrap();
        let sig2 = threshold_blind_sign(&keyset, &[1, 2], message).unwrap();

        // Both valid but different (different nonces and blinding)
        assert!(schnorr_blind::verify(&keyset.group_public, message, &sig1));
        assert!(schnorr_blind::verify(&keyset.group_public, message, &sig2));
        assert_ne!(sig1, sig2);
    }

    #[test]
    fn test_many_signatures() {
        let keyset = dealer_keygen(2, 3);
        for i in 0..15 {
            let msg = format!("token-{}", i);
            let sig = threshold_blind_sign(&keyset, &[1, 3], msg.as_bytes()).unwrap();
            assert!(
                schnorr_blind::verify(&keyset.group_public, msg.as_bytes(), &sig),
                "failed at i={}",
                i
            );
        }
    }
}
